### ISSUE TITLE
Incorrect example code

### ISSUE THREAD

**Issue by nkhosla91** [learn-co-curriculum/react-async-readme#7]
```
headers: {
      'Content-Type: application/json'
},
```

Should be:
```
headers: {
      'Content-Type': 'application/json'
},
```

**Comment by maxwellbenton** [comment]
Hi @nkhosla91,

Thank you for opening this issue. I've taken a look at this lesson, but I am unable to locate the error you are seeing. On this lesson's Readme, the only reference to `headers` in code appears to show the correct syntax:

```
handleSubmit = event => {
  event.preventDefault()
  fetch('the server URL', {
    method: "POST",
    headers: {
      "Content-Type": "application/json"
    },
    body: JSON.stringify(this.state)
  })
}
```

Is there something that I am missing or is it possible this error is located on another lesson?

Since I am unable to find any issue with this lesson's code snippets, I am going to close this issue. However, if you have any additional information regarding this issue or where in the lesson it is located, please feel free to reopen this and I will be happy to take another look.

Thank you!
